// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/littlebluewhite/schedule_task_command/dal/model"
)

func newParserReturn(db *gorm.DB, opts ...gen.DOOption) parserReturn {
	_parserReturn := parserReturn{}

	_parserReturn.parserReturnDo.UseDB(db, opts...)
	_parserReturn.parserReturnDo.UseModel(&model.ParserReturn{})

	tableName := _parserReturn.parserReturnDo.TableName()
	_parserReturn.ALL = field.NewAsterisk(tableName)
	_parserReturn.ID = field.NewInt32(tableName, "id")
	_parserReturn.Name = field.NewString(tableName, "name")
	_parserReturn.Key = field.NewString(tableName, "key")
	_parserReturn.SearchRule = field.NewString(tableName, "search_rule")
	_parserReturn.CommandTemplateID = field.NewInt32(tableName, "command_template_id")

	_parserReturn.fillFieldMap()

	return _parserReturn
}

type parserReturn struct {
	parserReturnDo parserReturnDo

	ALL               field.Asterisk
	ID                field.Int32
	Name              field.String
	Key               field.String
	SearchRule        field.String
	CommandTemplateID field.Int32

	fieldMap map[string]field.Expr
}

func (p parserReturn) Table(newTableName string) *parserReturn {
	p.parserReturnDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p parserReturn) As(alias string) *parserReturn {
	p.parserReturnDo.DO = *(p.parserReturnDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *parserReturn) updateTableName(table string) *parserReturn {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt32(table, "id")
	p.Name = field.NewString(table, "name")
	p.Key = field.NewString(table, "key")
	p.SearchRule = field.NewString(table, "search_rule")
	p.CommandTemplateID = field.NewInt32(table, "command_template_id")

	p.fillFieldMap()

	return p
}

func (p *parserReturn) WithContext(ctx context.Context) *parserReturnDo {
	return p.parserReturnDo.WithContext(ctx)
}

func (p parserReturn) TableName() string { return p.parserReturnDo.TableName() }

func (p parserReturn) Alias() string { return p.parserReturnDo.Alias() }

func (p parserReturn) Columns(cols ...field.Expr) gen.Columns {
	return p.parserReturnDo.Columns(cols...)
}

func (p *parserReturn) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *parserReturn) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 5)
	p.fieldMap["id"] = p.ID
	p.fieldMap["name"] = p.Name
	p.fieldMap["key"] = p.Key
	p.fieldMap["search_rule"] = p.SearchRule
	p.fieldMap["command_template_id"] = p.CommandTemplateID
}

func (p parserReturn) clone(db *gorm.DB) parserReturn {
	p.parserReturnDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p parserReturn) replaceDB(db *gorm.DB) parserReturn {
	p.parserReturnDo.ReplaceDB(db)
	return p
}

type parserReturnDo struct{ gen.DO }

func (p parserReturnDo) Debug() *parserReturnDo {
	return p.withDO(p.DO.Debug())
}

func (p parserReturnDo) WithContext(ctx context.Context) *parserReturnDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p parserReturnDo) ReadDB() *parserReturnDo {
	return p.Clauses(dbresolver.Read)
}

func (p parserReturnDo) WriteDB() *parserReturnDo {
	return p.Clauses(dbresolver.Write)
}

func (p parserReturnDo) Session(config *gorm.Session) *parserReturnDo {
	return p.withDO(p.DO.Session(config))
}

func (p parserReturnDo) Clauses(conds ...clause.Expression) *parserReturnDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p parserReturnDo) Returning(value interface{}, columns ...string) *parserReturnDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p parserReturnDo) Not(conds ...gen.Condition) *parserReturnDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p parserReturnDo) Or(conds ...gen.Condition) *parserReturnDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p parserReturnDo) Select(conds ...field.Expr) *parserReturnDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p parserReturnDo) Where(conds ...gen.Condition) *parserReturnDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p parserReturnDo) Order(conds ...field.Expr) *parserReturnDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p parserReturnDo) Distinct(cols ...field.Expr) *parserReturnDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p parserReturnDo) Omit(cols ...field.Expr) *parserReturnDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p parserReturnDo) Join(table schema.Tabler, on ...field.Expr) *parserReturnDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p parserReturnDo) LeftJoin(table schema.Tabler, on ...field.Expr) *parserReturnDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p parserReturnDo) RightJoin(table schema.Tabler, on ...field.Expr) *parserReturnDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p parserReturnDo) Group(cols ...field.Expr) *parserReturnDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p parserReturnDo) Having(conds ...gen.Condition) *parserReturnDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p parserReturnDo) Limit(limit int) *parserReturnDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p parserReturnDo) Offset(offset int) *parserReturnDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p parserReturnDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *parserReturnDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p parserReturnDo) Unscoped() *parserReturnDo {
	return p.withDO(p.DO.Unscoped())
}

func (p parserReturnDo) Create(values ...*model.ParserReturn) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p parserReturnDo) CreateInBatches(values []*model.ParserReturn, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p parserReturnDo) Save(values ...*model.ParserReturn) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p parserReturnDo) First() (*model.ParserReturn, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ParserReturn), nil
	}
}

func (p parserReturnDo) Take() (*model.ParserReturn, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ParserReturn), nil
	}
}

func (p parserReturnDo) Last() (*model.ParserReturn, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ParserReturn), nil
	}
}

func (p parserReturnDo) Find() ([]*model.ParserReturn, error) {
	result, err := p.DO.Find()
	return result.([]*model.ParserReturn), err
}

func (p parserReturnDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ParserReturn, err error) {
	buf := make([]*model.ParserReturn, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p parserReturnDo) FindInBatches(result *[]*model.ParserReturn, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p parserReturnDo) Attrs(attrs ...field.AssignExpr) *parserReturnDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p parserReturnDo) Assign(attrs ...field.AssignExpr) *parserReturnDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p parserReturnDo) Joins(fields ...field.RelationField) *parserReturnDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p parserReturnDo) Preload(fields ...field.RelationField) *parserReturnDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p parserReturnDo) FirstOrInit() (*model.ParserReturn, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ParserReturn), nil
	}
}

func (p parserReturnDo) FirstOrCreate() (*model.ParserReturn, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ParserReturn), nil
	}
}

func (p parserReturnDo) FindByPage(offset int, limit int) (result []*model.ParserReturn, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p parserReturnDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p parserReturnDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p parserReturnDo) Delete(models ...*model.ParserReturn) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *parserReturnDo) withDO(do gen.Dao) *parserReturnDo {
	p.DO = *do.(*gen.DO)
	return p
}
