// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCounter = "counter"

// Counter mapped from table <counter>
type Counter struct {
	Name  string `gorm:"column:name;primaryKey" json:"name"`
	Value int32  `gorm:"column:value;not null" json:"value"`
}

// TableName Counter's table name
func (*Counter) TableName() string {
	return TableNameCounter
}
