// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameParserReturn = "parser_return"

// ParserReturn mapped from table <parser_return>
type ParserReturn struct {
	ID                int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name              string `gorm:"column:name;not null" json:"name"`
	Key               string `gorm:"column:key;not null" json:"key"`
	SearchRule        string `gorm:"column:search_rule;not null" json:"search_rule"`
	CommandTemplateID int32  `gorm:"column:command_template_id;not null" json:"command_template_id"`
}

// TableName ParserReturn's table name
func (*ParserReturn) TableName() string {
	return TableNameParserReturn
}
