// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"encoding/json"
)

const TableNameStageItem = "stage_item"

// StageItem mapped from table <stage_item>
type StageItem struct {
	ID                int32           `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name              string          `gorm:"column:name;not null" json:"name"`
	StageNumber       int32           `gorm:"column:stage_number;not null" json:"stage_number"`
	Mode              string          `gorm:"column:mode;not null" json:"mode"`
	CommandTemplateID int32           `gorm:"column:command_template_id;not null" json:"command_template_id"`
	Tags              json.RawMessage `gorm:"column:tags;default:json_array()" json:"tags"`
	Variable          json.RawMessage `gorm:"column:variable;default:json_object()" json:"variable"`
	Parser            json.RawMessage `gorm:"column:parser;default:json_object()" json:"parser"`
	CommandTemplate   CommandTemplate `gorm:"foreignKey:command_template_id" json:"command_template"`
}

// TableName StageItem's table name
func (*StageItem) TableName() string {
	return TableNameStageItem
}
