// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTaskTemplateStage = "task_template_stage"

// TaskTemplateStage mapped from table <task_template_stage>
type TaskTemplateStage struct {
	TaskTemplateID int32 `gorm:"column:task_template_id;primaryKey" json:"task_template_id"`
	TaskStageID    int32 `gorm:"column:task_stage_id;primaryKey" json:"task_stage_id"`
}

// TableName TaskTemplateStage's table name
func (*TaskTemplateStage) TableName() string {
	return TableNameTaskTemplateStage
}
